language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
dist: xenial   # will be required for Python >= 3.7
install:
  - pip install -e .
  - pip install -r requirements-test.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=messytables
after_success:
  - coveralls
